### PR TITLE
README.md: add missing touch instruction for native build

### PR DESCRIPTION
**Pull request by alonblade**
Hi, very cool project! I've added a missing touch instruction to the instructions for building without docker. Otherwise they worked like a charm. I also had to increase the loop from 10000 to 1000000 (100 fold) to actually see the "welcome" message but probably the nicest fix for this is to implement a timer interrupt (didn't read enough of the code to see if that is already done).

Alon

### CODE REVIEW

**Comment by trusch** [comment]
Hey @alonblade! Why do you need this touch when building manually? This file is just a hint for Make that the buildimage already exists, but since you are building manually you shouldn't need it.

Though I'm glad you like the project :) There is no timer now, but you could start with writing a future factory that multiplexes the tick stream from the timer interrupts. The ticks are coming with 18Hz so you could build a timer API on top of that.

**Comment by alonblade** [comment]
The touch is required to appease "make run" since otherwise the chain is
(target -> requirement):

run -> snakeos.img -> .build-image

and singe .build-image does not exist, the rule is invoked, which is
opposite of what we want.

**Comment by trusch** [comment]
@alonblade ah, now I get what you mean. I thought by not using podman and buildah you would completely opt-out using the Makefile. The only thing you need to do after building the image is to boot it using qemu, and you don't have to use make at all. Just go with the qemu call mentioned in the Readme.

Could you, instead of the touch command, add some more sentences to the run-section of the Readme to make that more clear?

Btw. If you are on Linux, try out podman ;)

**Comment by alonblade** [comment]
I have used podman a bit, it is nice when it works, but it can be much
slower, depending on the backend, and I don't have the option of using
fedora (where I assume it rocks), and besides I prefer to not use
chroots/containers at all if I can (rust makes it pretty easy usually).

Probably won't get to updating the README. Really just change the line
saying "make run" for the not-podman case and you are done.

**Pull request closed without merging**
